config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :users, only: [:show] do
  #   resources :list, except: [:edit :update]
  # end
  # lists index create new show
  resources :lists, only: [:index, :create, :new, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(@bookmark[:list_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id]).destroy
    redirect_to list_path(@bookmark[:list_id])
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end
  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.input :movie_id, collection: @movies %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container bg-light cards">
  <!--<ol> -->
    <% @lists.each do |list| %>
      <% if list.photo.key %>
        <%= link_to list_path(list[:id]) do %>

          <!-- <li class="link-secondary"><%= link_to list.name, list_path(list[:id]), class: "link-secondary"  %></li> -->
          <div class="card-category"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <p class="link-white" ><%= list.name %></p>
          </div>
        <% end %>

      <% end %>

    <%end%>
  <!--</ol> -->
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
    <%= f.input :name %>
     <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
 <!--
  <ol>
    <% @list.bookmarks.each do |bookmark| %>

      <li class="link-secondary"><%= link_to bookmark.movie.title, list_path(bookmark[:id]), class: "link-secondary"  %></li>

    <%end%>
  </ol>
  <div class="cards">
   <% @list.bookmarks.each do |bookmark| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= bookmark.movie.poster_url %>)">
      <%= bookmark.movie.title %>
    </div>
    <%end%>
  </div>
-->
<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>

      <div class="card-trip">
      <img src=<%= bookmark.movie.poster_url %> />
      <div class="card-trip-infos">
        <div>
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.movie.overview %></p>
        </div>
        <%# <h2 class="card-trip-pricing">£99.99</h2> %>
        <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      </div>
    </div>
   <%end%>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-secondary bg-secondary">
  <div class="container">
    <%= link_to "Home", lists_path, class: "navbar-brand link-light" %>
    <%= link_to 'New List', new_list_path, class: 'btn btn-secondary border'  %>
  </div>
</nav>